export const LoanErrors = {
  INVALID_STRUCTURE: { code: 'INVALID_STRUCTURE', status: 400 },
  INVALID_LOAN_ID: { code: 'INVALID_LOAN_ID', status: 400 },
  INVALID_FINANCIAL_PROFILE_ID: { code: 'INVALID_FINANCIAL_PROFILE_ID', status: 400 },
  INVALID_START_DATE: { code: 'INVALID_START_DATE', status: 400 },
  INVALID_TERM: { code: 'INVALID_TERM', status: 400 },
  INVALID_PRINCIPAL: { code: 'INVALID_PRINCIPAL', status: 400 },
  INVALID_RATE: { code: 'INVALID_RATE', status: 400 },
  INVALID_PAYMENT_FREQUENCY: { code: 'INVALID_PAYMENT_FREQUENCY', status: 400 },
  INVALID_COMPOUNDING_FREQUENCY: { code: 'INVALID_COMPOUNDING_FREQUENCY', status: 400 },
  INVALID_GRACE_PERIOD: { code: 'INVALID_GRACE_PERIOD', status: 400 },
  INVALID_BALLOON_PAYMENT: { code: 'INVALID_BALLOON_PAYMENT', status: 400 },
  INVALID_LOAN_TYPE: { code: 'INVALID_LOAN_TYPE', status: 400 },
  INVALID_CURRENCY: { code: 'INVALID_CURRENCY', status: 400 }
};
