export const ScheduleErrors = {
  CREATE: {
    INVALID_INPUT:    "SCHEDULE_CREATE_INVALID_INPUT",
    INVALID_ID:       "SCHEDULE_CREATE_INVALID_ID",
    INVALID_LOAN_ID:  "SCHEDULE_CREATE_INVALID_LOAN_ID",
    INVALID_PLAN:     "SCHEDULE_CREATE_INVALID_PLAN",
    INVALID_START_DATE:"SCHEDULE_CREATE_INVALID_START_DATE",
    INVALID_TOTAL_AMOUNT:"SCHEDULE_CREATE_INVALID_TOTAL_AMOUNT",
    INVALID_CURRENCY: "SCHEDULE_CREATE_INVALID_CURRENCY",
    INVALID_INSTALLMENTS:"SCHEDULE_CREATE_INVALID_INSTALLMENTS"
  },

  READ: {
    INVALID_ID: "SCHEDULE_READ_INVALID_ID",
    NOT_FOUND:  "SCHEDULE_READ_NOT_FOUND"
  },

  UPDATE: {
    INVALID_INPUT:       "SCHEDULE_UPDATE_INVALID_INPUT",
    INVALID_ID:          "SCHEDULE_UPDATE_INVALID_ID",
    INVALID_PLAN:        "SCHEDULE_UPDATE_INVALID_PLAN",
    INVALID_START_DATE:  "SCHEDULE_UPDATE_INVALID_START_DATE",
    INVALID_TOTAL_AMOUNT:"SCHEDULE_UPDATE_INVALID_TOTAL_AMOUNT",
    INVALID_CURRENCY:    "SCHEDULE_UPDATE_INVALID_CURRENCY",
    INVALID_INSTALLMENTS:"SCHEDULE_UPDATE_INVALID_INSTALLMENTS",
    NOT_FOUND:           "SCHEDULE_UPDATE_NOT_FOUND"
  },

  DELETE: {
    INVALID_ID: "SCHEDULE_DELETE_INVALID_ID",
    NOT_FOUND:  "SCHEDULE_DELETE_NOT_FOUND"
  }
};
